version: '2'
services:
  mariadb:
    user: root
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=admin
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '~/Moodle:/bitnami'
  moodle:
    user: root
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=admin
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8085:80'
      - '443:443'
    volumes:
      - '~/Moodle:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local