version: '2.0'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=admin
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    networks: 
      - moodle
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=admin
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - moodle

# version: '2.1'
# services:
#   mariadb:
#     image: 'bitnami/mariadb:latest'
#     environment:
#       - MARIADB_USER=admin
#       - MARIADB_DATABASE=bitnami_moodlem
#       - ALLOW_EMPTY_PASSWORD=yes
#     volumes:
#       - 'C:/HQS Data/Docker/Moodle:/bitnami'
# volumes:
#   mariadb_data:
#     driver: local